### ISSUE TITLE
Play

### ISSUE THREAD

**Issue by DidItWork** [DidItWork/Sigma-Zero#21]
Function to play a game, taking in inputs from two agents. Utilised by the GUI object and benchmarking.

**Comment by chuanshaof** [comment]
def play(gui=None):
        
    gameobject = ChessTensor()

    while game is not over:

        ask gui to print board state

        if current player is human
            wait for user input
        else if current player is Model
            get board representation from gameobject
            do mcts
            wait for user input or play after time delay
        else
            get move from sf
            wait for user input or play after time delay
        
        push move to gameobject

        push move to board

class GUI:

    asldkfja;slkdf
